import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useWallet } from "@solana/wallet-adapter-react";

const AdminHome: NextPage = () => {
  const { publicKey, wallet } = useWallet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!publicKey ? (
        <main className={styles.main}>Not registered</main>
      ) : (
        <main className={styles.main}>
          <h1 className={styles.title}>Admin site</h1>
          <div className={styles.grid}>
            <a href="admin/games-settings" className={styles.card}>
              <h2>Settings &rarr;</h2>
              <p>Default configuration for games.</p>
            </a>
          </div>
          <div className={styles.grid}>
            <a href="admin/game" className={styles.card}>
              <h2>New Game</h2>
              <p>Create a new game.</p>
            </a>
          </div>
        </main>
      )}
    </div>
  );
};

export default AdminHome;
