import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useWallet } from "@solana/wallet-adapter-react";

const Home: NextPage = () => {
  const { publicKey, wallet } = useWallet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!publicKey ? (
        <main className={styles.main}>Not registered</main>
      ) : (
        <main className={styles.main}>
          <h1 className={styles.title}>List of Games</h1>
          <div className={styles.grid}>
            <Link href="/admin" passHref>
              <a className={styles.card}>
                <h2>Admin &rarr;</h2>
                <p>administration page</p>
              </a>
            </Link>
          </div>
        </main>
      )}
    </div>
  );
};

export default Home;
